Conduct\BlogBundle\Entity\Comment:
    type: entity
    table: Comment
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: '255'
        authorEmail:
            type: string
            length: '255'
            column: author_email
        authorUrl:
            type: string
            length: '255'
            column: author_url
        authorIp:
            type: string
            length: '100'
            column: author_ip
        date:
            type: datetime
        content:
            type: text
        approved:
            type: boolean
        type:
            type: string
            length: '20'
    manyToOne:
        post:
            targetEntity: Conduct\BlogBundle\Entity\Post

    lifecycleCallbacks: {  }
