Conduct\BlogBundle\Entity\Post:
    type: entity
    table: Post
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        name:
            type: string
            length: '255'
        content:
            type: text
        postDate:
            type: datetime
            column: post_date
        postExcerpt:
            type: string
            length: '255'
            column: post_excerpt
        postStatus:
            type: integer
            column: post_status
        postModified:
            type: datetime
            column: post_modified
    oneToMany:
        comments:
            targetEntity: Conduct\BlogBundle\Entity\Comment
            mappedBy: post
    oneToMany:
        postmetas:
            targetEntity: Conduct\BlogBundle\Entity\Postmeta
            mappedBy: post
    manyToOne:
        category:
             targetEntity: Conduct\BlogBundle\Entity\Category
             inversedBy: posts
             joinColumn:
                 name: category_id
                 referencedColumnName: id
        user:
            targetEntity: Acme\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id


    lifecycleCallbacks: {  }
